env:
  TZ: Asia/Ho_Chi_Minh

task:
  name: "Ubuntu SSH"
  timeout_in: 120m  
  container:
      image: ubuntu:latest
      cpu: 8
      memory: 32G
  
  Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - df -h
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio ccache neofetch -y
       - sudo apt install python-is-python3 -y
       - git config --global user.name "HoangLong"
       - git config --global user.email "hoanglong.wr.q@gmail.com"
       - ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""
  
  Sync_script:
       - mkdir $HOME/bin
       - curl https://storage.googleapis.com/git-repo-downloads/repo > $HOME/bin/repo
       - chmod a+x $HOME/bin/repo
       - export PATH="$PATH:$HOME/bin"
       - mkdir ~/Dot
       - cd ~/Dot
       - repo init --depth=1 --no-repo-verify -u https://github.com/DotOS/manifest.git -b dot12.1 -g default,-mips,-darwin,-notdefault
       - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
       - git clone https://gitlab.com/TipzTeam/android-trees/android_device_cyanogen_msm8916-common -b lineage-19.1 device/cyanogen/msm8916-common
       - git clone https://github.com/VR-HoangLong/android_device_oppo_A37 -b lineage-19.1 device/oppo/A37
       - git clone https://gitlab.com/TipzTeam/android-trees/android_kernel_oppo_msm8916 kernel/oppo/msm8939
       - git clone https://gitlab.com/TipzTeam/android-trees/proprietary_vendor_oppo_A37 -b lineage-19.1 vendor/oppo

  Build_script:
       - source build/envsetup.sh
       - lunch dot_A37-user
       - make bacon
