env:
  TZ: Asia/Ho_Chi_Minh
  rclone_config: ENCRYPTED[0621cf9b7de48fed10dd63bb69af0e526158192037a931274bef9cbf4009f7d15835e2741e94a7533f390f3112a7bca0]

task:
  name: "Ubuntu SSH"
  timeout_in: 120m  
  container:
      image: ubuntu:latest
      cpu: 8
      memory: 32G
  
  Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git bc bison build-essential pigz ccache curl flex g++-multilib grep gcc-multilib ccache lib32ncurses5-dev lib32readline-dev lib32z1-dev aria2 curl wget rsync zip unzip lzma cpio neofetch libc6-dev-i386 libncurses5-dev libncurses5 -y
       - sudo apt install python-is-python3 -y
       - git config --global user.name "VR-HoangLong"
       - git config --global user.email "+hoanglong@users.noreply.github.com"
       - ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""
       - curl https://rclone.org/install.sh | sudo bash

  Sync_script:
       - mkdir $HOME/bin
       - curl https://storage.googleapis.com/git-repo-downloads/repo > $HOME/bin/repo
       - chmod a+x $HOME/bin/repo
       - export PATH="$PATH:$HOME/bin"
       - mkdir ~/Lineage ~/LineageCCache
       - cd ~/Lineage
       - repo init --depth=1 --no-repo-verify -u https://github.com/LineageOS/android.git -b lineage-19.1 -g default,-mips,-darwin,-notdefault
       - repo sync -c --no-clone-bundle --no-tags --prune --force-sync -j33
       - git clone https://github.com/VR-HoangLong/android_device_vsmart_V430A -b lineage-19.1-q device/vsmart/V430A
       - git clone https://github.com/VR-HoangLong/android_vendor_vsmart_V430A -b twelve vendor/vsmart/V430A

  SDK_script:
       - wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
       - unzip platform-tools-latest-linux.zip -d ~
       - export PATH="\$HOME/platform-tools:\$PATH"

  Setup_Rclone_script:
       - mkdir -p ~/.config/rclone
       - echo "$rclone_config" > ~/.config/rclone/rclone.conf

  Build_script:
       - cd ~/Lineage
       - export PATH="$PATH:$HOME/bin"
       - sudo ln -s /proc/self/mounts /etc/mtab
       - export CCACHE_DIR=~/LineageCCache/cache
       - export CCACHE_EXEC=$(which ccache)
       - export USE_CCACHE=1
       - . build/envsetup.sh
       - lunch lineage_V430A-userdebug
       - make bacon -j31
