env:
  TZ: Asia/Ho_Chi_Minh

task:
  name: "Ubuntu SSH"
  timeout_in: 120m  
  container:
      image: ubuntu:latest
      cpu: 8
      memory: 32G
  
  Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git bc bison build-essential ccache curl flex g++-multilib grep gcc-multilib ccache lib32ncurses5-dev lib32readline-dev lib32z1-dev aria2 curl wget rsync zip unzip lzma cpio neofetch libc6-dev-i386 libncurses5-dev libncurses5 -y
       - sudo apt install python-is-python3 -y
       - git config --global user.name "VR-HoangLong"
       - git config --global user.email "+hoanglong@users.noreply.github.com"
       - ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""
       - curl https://rclone.org/install.sh | sudo bash

  Sync_script:
       - mkdir $HOME/bin
       - curl https://storage.googleapis.com/git-repo-downloads/repo > $HOME/bin/repo
       - chmod a+x $HOME/bin/repo
       - export PATH="$PATH:$HOME/bin"
       - mkdir ~/Lineage ~/LineageCCache
       - cd ~/Lineage
       - repo init --depth=1 --no-repo-verify -u https://github.com/LineageOS/android.git -b lineage-17.1 -g default,-mips,-darwin,-notdefault
       - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j33
       - git clone https://github.com/VR-HoangLong/sm6150-common-line -b master device/vsmart/sm6150-common
       - git clone https://github.com/VR-HoangLong/v620a-line -b master device/vsmart/V620A
       - git clone https://github.com/thinhx2/android_vendor_vsmart_sm6150-common -b master vendor/vsmart/sm6150-common
       - git clone https://github.com/thinhx2/android_vendor_vsmart_V620A -b mkq vendor/vsmart/V620A

  SDK_script:
       - wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
       - unzip platform-tools-latest-linux.zip -d ~
       - export PATH="\$HOME/platform-tools:\$PATH"

  Build_script:
       - cd ~/Lineage
       - export PATH="$PATH:$HOME/bin"
       - export CCACHE_DIR=~/LineageCCache/cache
       - export CCACHE_EXEC=$(which ccache)
       - export USE_CCACHE=1
       - source build/envsetup.sh
       - lunch lineage_V620A-userdebug
       - make api-stubs-docs
       - make hiddenapi-lists-docs
       - make system-api-stubs-docs
       - make test-api-stubs-docs
       - ccache -s
