env:
  TZ: Asia/Ho_Chi_Minh

task:
  name: "Ubuntu SSH"
  timeout_in: 120m  
  container:
      image: ubuntu:latest
      cpu: 8
      memory: 32G
  
  Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - df -h
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git bc bison build-essential ccache curl flex g++-multilib gcc-multilib ccache lib32ncurses5-dev lib32readline-dev lib32z1-dev aria2 curl wget rsync zip unzip lzma cpio ccache neofetch libc6-dev-i386 libncurses5-dev libncurses5 -y
       - sudo apt install python-is-python3 -y
       - git config --global user.name "HoangLong"
       - git config --global user.email "hoanglong.wr.q@gmail.com"
       - ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""
  
  Sync_script:
       - mkdir $HOME/bin
       - curl https://storage.googleapis.com/git-repo-downloads/repo > $HOME/bin/repo
       - chmod a+x $HOME/bin/repo
       - export PATH="$PATH:$HOME/bin"
       - mkdir ~/RR
       - cd ~/RR
       - repo init --depth=1 --no-repo-verify -u https://github.com/CarbonROM/android.git -b cr-8.0 -g default,-mips,-darwin,-notdefault
       - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j33
       - git clone https://github.com/VR-HoangLong/sm6150-common-line -b master device/vsmart/sm6150-common
       - git clone https://github.com/thinhx2/v620a-line -b carbon-ten device/vsmart/V620A
       - git clone https://github.com/thinhx2/android_vendor_vsmart_sm6150-common -b master vendor/vsmart/sm6150-common
       - git clone https://github.com/thinhx2/android_vendor_vsmart_V620A -b mkq vendor/vsmart/V620A


  SDK_script:
       - wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
       - unzip platform-tools-latest-linux.zip -d ~
       - export PATH="\$HOME/platform-tools:\$PATH"

  Build_script:
       - cd ~/RR
       - source build/envsetup.sh
       - lunch carbon_V620A-eng
       - make carbon -j31
